"""Build reproducible offline plugin and release assets using the Python standard library."""
import base64
import gzip
import hashlib
import io
import json
from pathlib import Path
import tarfile

ROOT = Path(__file__).resolve().parent.parent


def main():
    version = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))["version"]
    resources = ROOT / "resources"
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode="w", format=tarfile.USTAR_FORMAT) as archive:
        items = [(path.relative_to(resources).as_posix(), path.read_bytes()) for path in sorted(resources.rglob("*")) if path.is_file() and path.name != "install.sh"]
        items.append(("VERSION", (version + "\n").encode()))
        for name, data in sorted(items):
            info = tarfile.TarInfo("wg_res/" + name)
            info.size = len(data)
            info.mode = 0o755 if name.endswith(".sh") or name == "bin/wg" else 0o600
            info.mtime = 0
            info.uid = info.gid = 0
            archive.addfile(info, io.BytesIO(data))
    package = gzip.compress(raw.getvalue(), compresslevel=9, mtime=0)
    digest = hashlib.sha256(package).hexdigest()
    config = (ROOT / "src/config.cjs").read_text(encoding="utf-8")
    install = (resources / "scripts/common.sh").read_text(encoding="utf-8") + "\n" + (resources / "install.sh").read_text(encoding="utf-8")
    constants = {"VERSION": version, "EMBEDDED_PACKAGE": base64.b64encode(package).decode(), "PACKAGE_SHA256": digest, "INSTALL_SCRIPT": install}
    generated = "//<script>\n// Generated by tools/build.py; edit src/ and resources/ instead.\n(async () => {\n\"use strict\";\n"
    generated += "\n".join("const " + name + " = " + json.dumps(value, ensure_ascii=False) + ";" for name, value in constants.items())
    generated += "\nconst WGConfig = (() => { const module = { exports: {} };\n" + config + "\nreturn module.exports; })();\n"
    generated += (ROOT / "src/plugin.js").read_text(encoding="utf-8")
    generated += "\n})().catch((error) => console.error('WireGuard plugin initialization failed:', error));\n//</script>\n"
    (ROOT / "wireguard.js").write_text(generated, encoding="utf-8", newline="\n")
    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)
    (dist / "wireguard-resources.tar.gz").write_bytes(package)
    manifest = {"version": version, "resources": {"file": "wireguard-resources.tar.gz", "sha256": digest, "bytes": len(package)}, "plugin": {"file": "wireguard.js", "sha256": hashlib.sha256(generated.encode()).hexdigest()}, "wgBinary": {"origin": "Original user-provided wireguard.js bundle; upstream source and build provenance unverified", "sha256": hashlib.sha256((resources / "bin/wg").read_bytes()).hexdigest()}}
    (dist / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"Built v{version}: plugin {len(generated.encode())} bytes, resources {len(package)} bytes")
    print("Resource SHA-256:", digest)


if __name__ == "__main__":
    main()
